# -*- coding: utf-8 -*-
"""CumulativeSum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WzIo_Zzc0r1Fagurb68y1HjhAE4gV9wp
"""

import numpy as np
import matplotlib.pyplot as plt
import sys

n = int(input("Size of variable data stream: "))

th = int(input("Enter a threshold value: "))

x = np.random.randn(n)
g_neg = [0] * len(x)
g_pos = [0] * len(x)
s = [0]
ta = []

for i in range(1,len(x)):
  s.append(x[i] - x[i-1])
  g_pos[i] = g_pos[i-1] + s[i]
  if g_pos[i] < 0:
    g_pos[i] = 0
  g_neg[i] = g_neg[i-1] - s[i]
  if g_neg[i] < 0:
    g_neg[i] = 0
  if g_pos[i] > th or g_neg[i] > th:
    ta.append(i)
    g_pos[i] = 0
    g_neg[i] = 0

plt.plot(range(x.size), x, 'b-', lw=2)
plt.plot(ta, x[ta], 'o', mfc='r', mec='r')
plt.show()